CREATE TABLE "Matrices" ("matrixId" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "photo" BLOB);
CREATE TABLE "Transactions" ("transactionId" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "matrixId" INTEGER NOT NULL , "payerId" INTEGER NOT NULL , "payeeId" INTEGER NOT NULL , "amount" REAL NOT NULL );
CREATE TABLE "Users" ("userId" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "name" TEXT, "email" TEXT NOT NULL , "photo" BLOB);
CREATE TABLE "matrixUsers" ("matrixUserId" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "matrixId" INTEGER NOT NULL , "userId" INTEGER NOT NULL );
